/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Logic.Global;
import Logic.HNHotelsCom;
import Logic.Hotel;
import Logic.Reserve;
import Logic.Season;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;

/**
 *
 * @author Kimberly
 */
public class ReportsWindow extends javax.swing.JFrame {

    private final AdminWindow ancestor;
    private final Global global;
    public ReportsWindow(AdminWindow ancestor) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.ancestor = ancestor;
        this.global = Global.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCancelReserves = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCompleteReserves = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListHotelForReservations = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxHotelReport = new javax.swing.JComboBox();
        jComboBoxSeasonHotel = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListReservationSeason = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jButtonGenereate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Cancel reservations:");

        jScrollPane1.setViewportView(jListCancelReserves);

        jLabel1.setText("Complete reserves:");

        jScrollPane2.setViewportView(jListCompleteReserves);

        jLabel3.setText("Hotel with more reservations:");

        jScrollPane3.setViewportView(jListHotelForReservations);

        jLabel4.setText("Reservation for season:");

        jLabel5.setText("Hotel:");

        jComboBoxHotelReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHotelReportActionPerformed(evt);
            }
        });

        jComboBoxSeasonHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSeasonHotelActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jListReservationSeason);

        jLabel6.setText("Season:");

        jButtonGenereate.setText("Generate");
        jButtonGenereate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenereateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(jComboBoxHotelReport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxSeasonHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addComponent(jButtonGenereate))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxHotelReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSeasonHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonGenereate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        ancestor.setEnabled(true);
        this.dispose();
       
    }//GEN-LAST:event_jButtonBackActionPerformed
    public void chargeCancelReserves(){
        DefaultListModel model = new DefaultListModel();
        for(Reserve temporalReserve : global.getCancelReservationsList()){
            model.addElement(temporalReserve.getCode());
        }
        jListCancelReserves.setModel(model);
    }
    public void chargeCompleteReserves(){
        DefaultListModel model = new DefaultListModel();
        for(Reserve temporalReserve :  global.getCompleteReservationList()){
            model.addElement(temporalReserve.getCode());
        }
        jListCompleteReserves.setModel(model);
    }
    public void chargeHotelsForReserves(ArrayList<Hotel> list){
        DefaultListModel model = new DefaultListModel();
        for(Hotel temporalHotel : list){
            model.addElement(temporalHotel.getName()+" -Amount:"+temporalHotel.getNumberOfReservations());
        }
        jListHotelForReservations.setModel(model);
    }
    public void chargeComboWithHotels(){
        for(Hotel temporalHotel : global.getHotelsList()){
            jComboBoxHotelReport.addItem(temporalHotel.getName());
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       chargeCancelReserves();
       chargeCompleteReserves();
       chargeHotelsForReserves(orderHotels());
       chargeComboWithHotels();
    }//GEN-LAST:event_formWindowOpened
    private void chargeComboSeason(Hotel hotel){
        jComboBoxSeasonHotel.removeAllItems();
        for(Season temporalSeason : hotel.getSeasons()){
            if(hotel.getSeasons().isEmpty())
                return;
            else            
            jComboBoxSeasonHotel.addItem(temporalSeason.getCode());
            
        }
    }
    private void jComboBoxHotelReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHotelReportActionPerformed
        if(jComboBoxHotelReport.getSelectedItem()!= null){
            chargeComboSeason(HNHotelsCom.searchHotel(jComboBoxHotelReport.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_jComboBoxHotelReportActionPerformed
    
    private void chargeLisReservation(Season season){
        DefaultListModel model = new DefaultListModel();
        for(Reserve temporalReserve : season.getReservationList()){
            model.addElement(temporalReserve.getCode());
        }
        jListReservationSeason.setModel(model);
    }
    private void jComboBoxSeasonHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSeasonHotelActionPerformed
        Season season = HNHotelsCom.searchSeason(HNHotelsCom.searchHotel(jComboBoxHotelReport.getSelectedItem().toString())
        ,jComboBoxSeasonHotel.getSelectedItem().toString() );
        if(season==null){
            return;
        }
        chargeLisReservation(season);
    }//GEN-LAST:event_jComboBoxSeasonHotelActionPerformed

    private void jButtonGenereateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenereateActionPerformed
       
    }//GEN-LAST:event_jButtonGenereateActionPerformed
    public ArrayList<Hotel> orderHotels(){
        ArrayList<Hotel> results = new ArrayList();
        ArrayList<Hotel> clone = (ArrayList<Hotel>)global.getHotelsList().clone();
        if(clone.size() > 0){
            while(clone.size() > 0){
                int index = 0, high = 0;
                for(Hotel temporalHotel : clone){
                    if(temporalHotel.getReserveCount() > clone.get(high).getReserveCount()){
                        high = index;
                    }
                    index++;
                }
                results.add(clone.get(high));
                clone.remove(high);
            }
        }
        return results;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsWindow(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonGenereate;
    private javax.swing.JComboBox jComboBoxHotelReport;
    private javax.swing.JComboBox jComboBoxSeasonHotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListCancelReserves;
    private javax.swing.JList jListCompleteReserves;
    private javax.swing.JList jListHotelForReservations;
    private javax.swing.JList jListReservationSeason;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
